#pragma once

#include "global.h"

typedef enum IRC_Numeric
{
    /* 1. Server */

    RPL_WELCOME = 1,
    RPL_YOURHOST = 2,
    RPL_CREATED = 3,
    RPL_MYINFO = 4,
    RPL_ISUPPORT = 5,
    RPL_BOUNCE = 10,

    RPL_STATSCOMMANDS = 212,
    RPL_ENDOFSTATS = 219,
    RPL_UMODEIS = 221,
    RPL_STATSUPTIME = 242,

    RPL_LUSERCLIENT = 251,
    RPL_LUSEROP = 252,
    RPL_LUSERUNKNOWN = 253,
    RPL_LUSERCHANNELS = 254,
    RPL_LUSERME = 255,

    RPL_ADMINME = 256,
    RPL_ADMINLOC1 = 257,
    RPL_ADMINLOC2 = 258,
    RPL_ADMINEMAIL = 259,
    RPL_TRYAGAIN = 263,
    RPL_LOCALUSERS = 265,
    RPL_GLOBALUSERS = 266,

    RPL_VERSION = 351,
    RPL_INFO = 371,
    RPL_MOTD = 372,
    RPL_ENDOFINFO = 374,
    RPL_MOTDSTART = 375,
    RPL_ENDOFMOTD = 376,

    RPL_YOUREOPER = 381,
    RPL_REHASHING = 382,
    RPL_TIME = 391,

    /* 2. User */

    RPL_NONE = 300,
    RPL_AWAY = 301,
    RPL_USERHOST = 302,
    RPL_UNAWAY = 305,
    RPL_NOWAWAY = 306,

    RPL_WHOISREGNICK = 307,
    RPL_WHOISUSER = 311,
    RPL_WHOISSERVER = 312,
    RPL_WHOISOPERATOR = 313,
    RPL_WHOWASUSER = 314,
    RPL_ENDOFWHO = 315,
    RPL_WHOISIDLE = 317,
    RPL_ENDOFWHOIS = 318,
    RPL_WHOISCHANNELS = 319,
    RPL_WHOISSPECIAL = 320,

    RPL_WHOISACCOUNT = 330,
    RPL_WHOISACTUALLY = 338,

    RPL_WHOREPLY = 352,

    RPL_ENDOFWHOWAS = 369,

    RPL_WHOISCERTFP = 276,
    RPL_WHOISHOST = 378,
    RPL_WHOISMODES = 379,

    RPL_STARTTLS = 670,
    RPL_WHOISSECURE = 671,

    RPL_HELPSTART = 704,
    RPL_HELPTXT = 705,
    RPL_ENDOFHELP = 706,

    RPL_LOGGEDIN = 900,
    RPL_LOGGEDOUT = 901,
    RPL_SASLSUCCESS = 903,
    RPL_SASLMECHS = 908,

    /* 3. Channel */

    RPL_LISTSTART = 321,
    RPL_LIST = 322,
    RPL_LISTEND = 323,
    RPL_CHANNELMODEIS = 324,
    RPL_CREATIONTIME = 329,

    RPL_NOTOPIC = 331,
    RPL_TOPIC = 332,
    RPL_TOPICWHOTIME = 333,

    RPL_INVITELIST = 336,
    RPL_ENDOFINVITELIST = 337,
    RPL_INVITING = 341,

    RPL_INVEXLIST = 346,
    RPL_ENDOFINVEXLIST = 347,
    RPL_EXCEPTLIST = 348,
    RPL_ENDOFEXCEPTLIST = 349,

    RPL_NAMREPLY = 353,
    RPL_LINKS = 364,
    RPL_ENDOFLINKS = 365,
    RPL_ENDOFNAMES = 366,
    RPL_BANLIST = 367,
    RPL_ENDOFBANLIST = 368,

    /* 4. Errors */

    ERR_UNKNOWNERROR = 400,
    ERR_NOSUCHNICK = 401,
    ERR_NOSUCHSERVER = 402,
    ERR_NOSUCHCHANNEL = 403,
    ERR_CANNOTSENDTOCHAN = 404,
    ERR_TOOMANYCHANNELS = 405,
    ERR_WASNOSUCHNICK = 406,

    ERR_NOORIGIN = 409,
    ERR_NORECIPIENT = 411,
    ERR_NOTEXTTOSEND = 412,
    ERR_INPUTTOOLONG = 417,

    ERR_UNKNOWNCOMMAND = 421,
    ERR_NOMOTD = 422,

    ERR_NONICKNAMEGIVEN = 431,
    ERR_ERRONEUSNICKNAME = 432,
    ERR_NICKNAMEINUSE = 433,
    ERR_NICKCOLLISION = 436,

    ERR_USERNOTINCHANNEL = 441,
    ERR_NOTONCHANNEL = 442,
    ERR_USERONCHANNEL = 443,

    ERR_NOTREGISTERED = 451,
    ERR_NEEDMOREPARAMS = 461,
    ERR_ALREADYREGISTERED = 462,
    ERR_PASSWDMISMATCH = 464,
    ERR_YOUREBANNEDCREEP = 465,

    ERR_CHANNELISFULL = 471,
    ERR_UNKNOWNMODE = 472,
    ERR_INVITEONLYCHAN = 473,
    ERR_BANNEDFROMCHAN = 474,
    ERR_BADCHANNELKEY = 475,
    ERR_BADCHANMASK = 476,

    ERR_NOPRIVILEGES = 481,
    ERR_CHANOPRIVSNEEDED = 482,
    ERR_CANTKILLSERVER = 483,
    ERR_NOOPERHOST = 491,

    ERR_UMODEUNKNOWNFLAG = 501,
    ERR_USERSDONTMATCH = 502,
    ERR_HELPNOTFOUND = 524,
    ERR_INVALIDKEY = 525,

    ERR_STARTTLS = 691,
    ERR_INVALIDMODEPARAM = 696,
    ERR_NOPRIVS = 723,

    ERR_NICKLOCKED = 902,
    ERR_SASLFAIL = 904,
    ERR_SASLTOOLONG = 905,
    ERR_SASLABORTED = 906,
    ERR_SASLALREADY = 907,
} IRC_Numeric;

void NUMERIC_handle_WELCOME(IRC_Message *);
void NUMERIC_handle_YOURHOST(IRC_Message *);
void NUMERIC_handle_CREATED(IRC_Message *);
void NUMERIC_handle_MYINFO(IRC_Message *);
void NUMERIC_handle_ISUPPORT(IRC_Message *);
void NUMERIC_handle_BOUNCE(IRC_Message *);

void NUMERIC_handle_STATSCOMMANDS(IRC_Message *);
void NUMERIC_handle_ENDOFSTATS(IRC_Message *);
void NUMERIC_handle_UMODEIS(IRC_Message *);
void NUMERIC_handle_STATSUPTIME(IRC_Message *);

void NUMERIC_handle_LUSERCLIENT(IRC_Message *);
void NUMERIC_handle_LUSEROP(IRC_Message *);
void NUMERIC_handle_LUSERUNKNOWN(IRC_Message *);
void NUMERIC_handle_LUSERCHANNELS(IRC_Message *);
void NUMERIC_handle_LUSERME(IRC_Message *);

void NUMERIC_handle_ADMINME(IRC_Message *);
void NUMERIC_handle_ADMINLOC1(IRC_Message *);
void NUMERIC_handle_ADMINLOC2(IRC_Message *);
void NUMERIC_handle_ADMINEMAIL(IRC_Message *);
void NUMERIC_handle_TRYAGAIN(IRC_Message *);
void NUMERIC_handle_LOCALUSERS(IRC_Message *);
void NUMERIC_handle_GLOBALUSERS(IRC_Message *);

void NUMERIC_handle_VERSION(IRC_Message *);
void NUMERIC_handle_INFO(IRC_Message *);
void NUMERIC_handle_MOTD(IRC_Message *);
void NUMERIC_handle_ENDOFINFO(IRC_Message *);
void NUMERIC_handle_MOTDSTART(IRC_Message *);
void NUMERIC_handle_ENDOFMOTD(IRC_Message *);

void NUMERIC_handle_YOUREOPER(IRC_Message *);
void NUMERIC_handle_REHASHING(IRC_Message *);
void NUMERIC_handle_TIME(IRC_Message *);

void NUMERIC_handle_NONE(IRC_Message *);
void NUMERIC_handle_AWAY(IRC_Message *);
void NUMERIC_handle_USERHOST(IRC_Message *);
void NUMERIC_handle_UNAWAY(IRC_Message *);
void NUMERIC_handle_NOWAWAY(IRC_Message *);

void NUMERIC_handle_WHOISREGNICK(IRC_Message *);
void NUMERIC_handle_WHOISUSER(IRC_Message *);
void NUMERIC_handle_WHOISSERVER(IRC_Message *);
void NUMERIC_handle_WHOISOPERATOR(IRC_Message *);
void NUMERIC_handle_WHOWASUSER(IRC_Message *);
void NUMERIC_handle_ENDOFWHO(IRC_Message *);
void NUMERIC_handle_WHOISIDLE(IRC_Message *);
void NUMERIC_handle_ENDOFWHOIS(IRC_Message *);
void NUMERIC_handle_WHOISCHANNELS(IRC_Message *);
void NUMERIC_handle_WHOISSPECIAL(IRC_Message *);

void NUMERIC_handle_WHOISACCOUNT(IRC_Message *);
void NUMERIC_handle_WHOISACTUALLY(IRC_Message *);

void NUMERIC_handle_WHOREPLY(IRC_Message *);

void NUMERIC_handle_ENDOFWHOWAS(IRC_Message *);

void NUMERIC_handle_WHOISCERTFP(IRC_Message *);
void NUMERIC_handle_WHOISHOST(IRC_Message *);
void NUMERIC_handle_WHOISMODES(IRC_Message *);

void NUMERIC_handle_RPLSTARTTLS(IRC_Message *);
void NUMERIC_handle_WHOISSECURE(IRC_Message *);

void NUMERIC_handle_HELPSTART(IRC_Message *);
void NUMERIC_handle_HELPTXT(IRC_Message *);
void NUMERIC_handle_ENDOFHELP(IRC_Message *);

void NUMERIC_handle_LOGGEDIN(IRC_Message *);
void NUMERIC_handle_LOGGEDOUT(IRC_Message *);
void NUMERIC_handle_SASLSUCCESS(IRC_Message *);
void NUMERIC_handle_SASLMECHS(IRC_Message *);

void NUMERIC_handle_LISTSTART(IRC_Message *);
void NUMERIC_handle_LIST(IRC_Message *);
void NUMERIC_handle_LISTEND(IRC_Message *);
void NUMERIC_handle_CHANNELMODEIS(IRC_Message *);
void NUMERIC_handle_CREATIONTIME(IRC_Message *);

void NUMERIC_handle_NOTOPIC(IRC_Message *);
void NUMERIC_handle_TOPIC(IRC_Message *);
void NUMERIC_handle_TOPICWHOTIME(IRC_Message *);

void NUMERIC_handle_INVITELIST(IRC_Message *);
void NUMERIC_handle_ENDOFINVITELIST(IRC_Message *);
void NUMERIC_handle_INVITING(IRC_Message *);

void NUMERIC_handle_INVEXLIST(IRC_Message *);
void NUMERIC_handle_ENDOFINVEXLIST(IRC_Message *);
void NUMERIC_handle_EXCEPTLIST(IRC_Message *);
void NUMERIC_handle_ENDOFEXCEPTLIST(IRC_Message *);

void NUMERIC_handle_NAMREPLY(IRC_Message *);
void NUMERIC_handle_LINKS(IRC_Message *);
void NUMERIC_handle_ENDOFLINKS(IRC_Message *);
void NUMERIC_handle_ENDOFNAMES(IRC_Message *);
void NUMERIC_handle_BANLIST(IRC_Message *);
void NUMERIC_handle_ENDOFBANLIST(IRC_Message *);

void NUMERIC_handle_UNKNOWNERROR(IRC_Message *);
void NUMERIC_handle_NOSUCHNICK(IRC_Message *);
void NUMERIC_handle_NOSUCHSERVER(IRC_Message *);
void NUMERIC_handle_NOSUCHCHANNEL(IRC_Message *);
void NUMERIC_handle_CANNOTSENDTOCHAN(IRC_Message *);
void NUMERIC_handle_TOOMANYCHANNELS(IRC_Message *);
void NUMERIC_handle_WASNOSUCHNICK(IRC_Message *);

void NUMERIC_handle_NOORIGIN(IRC_Message *);
void NUMERIC_handle_NORECIPIENT(IRC_Message *);
void NUMERIC_handle_NOTEXTTOSEND(IRC_Message *);
void NUMERIC_handle_INPUTTOOLONG(IRC_Message *);

void NUMERIC_handle_UNKNOWNCOMMAND(IRC_Message *);
void NUMERIC_handle_NOMOTD(IRC_Message *);

void NUMERIC_handle_NONICKNAMEGIVEN(IRC_Message *);
void NUMERIC_handle_ERRONEUSNICKNAME(IRC_Message *);
void NUMERIC_handle_NICKNAMEINUSE(IRC_Message *);
void NUMERIC_handle_NICKCOLLISION(IRC_Message *);

void NUMERIC_handle_USERNOTINCHANNEL(IRC_Message *);
void NUMERIC_handle_NOTONCHANNEL(IRC_Message *);
void NUMERIC_handle_USERONCHANNEL(IRC_Message *);

void NUMERIC_handle_NOTREGISTERED(IRC_Message *);
void NUMERIC_handle_NEEDMOREPARAMS(IRC_Message *);
void NUMERIC_handle_ALREADYREGISTERED(IRC_Message *);
void NUMERIC_handle_PASSWDMISMATCH(IRC_Message *);
void NUMERIC_handle_YOUREBANNEDCREEP(IRC_Message *);

void NUMERIC_handle_CHANNELISFULL(IRC_Message *);
void NUMERIC_handle_UNKNOWNMODE(IRC_Message *);
void NUMERIC_handle_INVITEONLYCHAN(IRC_Message *);
void NUMERIC_handle_BANNEDFROMCHAN(IRC_Message *);
void NUMERIC_handle_BADCHANNELKEY(IRC_Message *);
void NUMERIC_handle_BADCHANMASK(IRC_Message *);

void NUMERIC_handle_NOPRIVILEGES(IRC_Message *);
void NUMERIC_handle_CHANOPRIVSNEEDED(IRC_Message *);
void NUMERIC_handle_CANTKILLSERVER(IRC_Message *);
void NUMERIC_handle_NOOPERHOST(IRC_Message *);

void NUMERIC_handle_UMODEUNKNOWNFLAG(IRC_Message *);
void NUMERIC_handle_USERSDONTMATCH(IRC_Message *);
void NUMERIC_handle_HELPNOTFOUND(IRC_Message *);
void NUMERIC_handle_INVALIDKEY(IRC_Message *);

void NUMERIC_handle_ERRSTARTTLS(IRC_Message *);
void NUMERIC_handle_INVALIDMODEPARAM(IRC_Message *);
void NUMERIC_handle_NOPRIVS(IRC_Message *);

void NUMERIC_handle_NICKLOCKED(IRC_Message *);
void NUMERIC_handle_SASLFAIL(IRC_Message *);
void NUMERIC_handle_SASLTOOLONG(IRC_Message *);
void NUMERIC_handle_SASLABORTED(IRC_Message *);
void NUMERIC_handle_SASLALREADY(IRC_Message *);